# Name of your application. Used to uniquely configure containers.
service: jupyterlab

# Name of the container image.
image: jan-kaczorowski/jupyterlab

servers:
  web:
    - 52.28.8.239

proxy:
  ssl: true
  host: jupyterlab.jankaczorowski.pl
  app_port: 8888
  healthcheck:
    path: /
    interval: 10
    timeout: 10

# Credentials for your image host.
registry:
  server: 546620766310.dkr.ecr.eu-west-1.amazonaws.com
  username: AWS
  password: <%= %x[AWS_PROFILE=privr aws ecr get-login-password --region eu-west-1].strip %>

builder:
  arch: amd64 # i'm building on Mac but deploying to Linux AMD64

env:
  clear:
    GRANT_SUDO: yes

ssh:
  user: ubuntu
  keys: [ "~/.ssh/my-aws.pem" ]

